name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dsound-api:latest

      - name: Logout from Docker Hub
        run: docker logout

      - name: SSH to Azure VM and run Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/dsound-api:latest
            sudo docker stop dsound-api || true
            sudo docker rm dsound-api || true
            sudo docker run -d --name dsound-api -p 8080:8080 -p 9090:9091 ${{ secrets.DOCKER_HUB_USERNAME }}/dsound-api:latest
            sudo docker logout